### ISSUE TITLE
❗ [버그][CI/CD] PR 시 안드로이드 테스트 빌드 문제

### ISSUE THREAD

**Issue by SeoHyun1024** [TEAM-ROMROM/RomRom-FE#26]
## 🗒️ 설명

- 현재 PR을 올리면 자동으로 안드로이드 테스트 빌드를 진행하는데 불필요한 플로우워크가 있습니다.
```yaml
      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run Flutter Tests  // 삭제 필요
        run: flutter test

      - name: Build APK (Test Build)
        run: flutter build apk --debug
```
- Run Flutter Tests 는 현재 앱의 빌드와는 관계가 없는 데모 코드를 실행시킵니다.
- `flutter test`실행시 돌아가는 test 코드
```dart
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility in the flutter_test package. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:romrom_fe/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp(
      initialScreen: Container(),
    ));

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
```
- 해당 코드를 참고하시면 본 프로젝트와는 관련없는 데모코드(카운터 테스트) 가 실행됩니다.

## ✅ 예상 동작

- PR을 올리면 정상적으로 디버그 빌드를 완료하여야 합니다.

## ⚙️ 환경 정보

- **OS**:
- **브라우저**:
- **기기**:

## 🙋‍♂️ 담당자

- **백엔드**: 이름
- **프론트엔드**: @SeoHyun1024
- **디자인**: 이름
