### ISSUE TITLE
⚙️ [기능추가][PR] Code Rabbit AI 봇 추가

### ISSUE THREAD

**Issue by Cassiiopeia** [TEAM-ROMROM/RomRom-FE#84]
## 📝 현재 문제점

- PR 리뷰를 제대로 도와줄 친구 데려왔습니다

## 🛠️ 해결 방안 / 제안 기능

- 프로젝트 루트 디렉토리에 다음 파일을 추가해야합니다
- 일단 현재 계정과 프로젝트를 연결해놓은 상태입니다
- 다음 설정파일로 한국어 등등 여러기능을 추가해야합니다

- 파일이름: .coderabbit.yaml
```
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
```

## 🙋‍♂️ 담당자

- 백엔드: 이름
- 프론트엔드: @Cassiiopeia 
- 디자인: 이름
