### ISSUE TITLE
⚙️ [기능추가][프로젝트] Github Copilot 프로젝트 설정 가이드 추가 및 Lint , 분석 설정 추가

### ISSUE THREAD

**Issue by Cassiiopeia** [TEAM-ROMROM/RomRom-FE#93]
## 📝 현재 문제점

- 프로젝트 고유의 특성을 살린 답변을 매번 작성해줘야하는 불편함이 있습니다
- 저희 프로젝트의 일관된 코드 스타일과 주석을 유지하기 위한 설정파일을 다음과 같이 추가할수있습니다.
- Lint , 분석 옵션이 존재하지않습니다. flutter analyze로 설정값을 확인해야하는 불편함이 있습니다

## 🛠️ 해결 방안 / 제안 기능

1. Lint 설정
```
# analysis_options.yaml (프로젝트 루트에 위치)
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: info
    fixme: warning

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - prefer_const_constructors
    - avoid_print
    - use_key_in_widget_constructors
    - prefer_descriptive_variable_names
    - always_put_required_named_parameters_first
    - sort_constructors_first
```
에디터 설정 (인텔리제이)
``` 
# .editorconfig (프로젝트 루트에 위치)
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.dart]
max_line_length = 100
```
2. Copilot config 파일 예시
```
## 5. Copilot 가이드 파일

```json
# .github/copilot/config.json
{
  "commentLanguage": "ko",
  "style": {
    "comments": {
      "classDoc": "/// {클래스설명}\n/// \n/// {추가설명}",
      "methodDoc": "/// {메소드설명}\n/// \n/// {매개변수설명}\n/// {반환값설명}",
      "todoFormat": "// TODO: {할일}",
      "fixmeFormat": "// FIXME: {수정사항}"
    },
    "naming": {
      "useDescriptiveNames": true,
      "avoidAbbreviations": true
    }
  }
}
``` 

그리고 추가로 app_icons.dart, app_colors.dart, app_theme.dart, app_urls.dart, 등을 자동으로 묶어서 고려하는 설정 파일을 추가해야합니다

## 🙋‍♂️ 담당자

- 백엔드: 이름
- 프론트엔드: @Cassiiopeia @SeoHyun1024 
- 디자인: 이름
